---

# RESOURCES ------------------------------ #
resources:
  # - name: source-code
  #   type: git
  #   source:
  #     uri: https://github.com/dgrebb/Snippets
  #     branch: master
  - name: source
    type: git
    source:
      branch: master
      uri: https://github.com/dgrebb/concourse-tasks.git
  - name: bluegreen
    type: keyval

# RESOURCE TYPES ------------------------- #
resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

# JOBS ----------------------------------- #
jobs:
  - name: make bluegreen
    plan:
    - get: source
    - task: make bluegreen
      file: source/tasks/bluegreen-task.yml
    - put: bluegreen
      params:
        file: bluegreen/keyval.properties

  - name: read bluegreen
    plan:
    - get: bluegreen
    - get: source
      passed:
      - make bluegreen
      trigger: true
    - task: convert keyvals
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        inputs:
        - name: source
        - name: bluegreen
        run:
          path: sh
          args:
          - -exc
          - |
            chmod +x source/tasks/keyvals-task.sh
            source/tasks/keyvals-task.sh
            echo "booyaa -> ${PROD_ENVIRONMENT}"

    - task: print bluegreen vals
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        inputs:
        - name: bluegreen
        run:
          path: sh
          args:
          - -exc
          - |
            cat bluegreen/keyval.properties
            echo "prod -> ${PROD_ENVIRONMENT}"

  # - name: echo file 
  #   plan:
  #   - get: source-code
  #   - task: eco
  #     config:
  #       platform: linux
  #       image_resource:
  #         type: docker-image
  #         source:
  #           repository: busybox
  #       inputs:
  #       - name: source-code
  #       outputs:
  #       - name: resources
  #       run:
  #         path: sh
  #         args:
  #         - -exec
  #         - |
  #           echo "blue" > ./resources/bluegreen
  #   - task: readfile
  #     config:
  #       platform: linux
  #       image_resource:
  #         type: docker-image
  #         source:
  #           repository: busybox
  #       inputs:
  #       - name: resources
  #       run:
  #         path: sh
  #         args:
  #         - -exec
  #         - |
  #           cat resources/bluegreen
            
  # - name: Read Persistent Resource
  #   plan:
  #   - get: source-code
  #     passed:
  #     - echo file
  #     trigger: true
  #   - task: print persistent bluegreen resource
  #     config:
  #       platform: linux
  #       image_resource:
  #         type: docker-image
  #         source:
  #           repository: busybox
  #       inputs:
  #       - name: source-code
  #       outputs:
  #       - name: bluegreen-resource
  #       run:
  #         path: sh
  #         args:
  #         - -exec
  #         - |
  #           ls -la
  #           echo 'something should happen here'
