---
platform: linux
image_resource:
    type: docker-image
    source:
      repository: busybox
outputs:
- name: bluegreen
run:
  path: sh
  args:
  - -exec
  - |
    FILE="bluegreen/keyval.properties"
    echo 'PROD_ENVIRONMENT="green"' >> $FILE
    echo 'SOMOTHER="value is stored here"' >> $FILE
