---
platform: linux
image_resource:
    type: docker-image
    source:
      repository: busybox
outputs:
- name: bluegreen
run:
  path: sh
  args:
  - -exec
  - |
    echo "deploying" > bluegreen/state.properties
    ls -la bluegreen
