---
platform: linux
image_resource:
    type: docker-image
    source:
      repository: busybox
outputs:
- name: bluegreen
run:
  path: sh
  args:
  - -exec
  - |
    echo "DEPLOYING=true" > bluegreen/keyval.properties
