---
platform: linux
image_resource:
    type: docker-image
    source:
      repository: busybox
inputs:
- name: bluegreen
outputs:
- name: bluegreen
run:
  path: sh
  args:
  - -exec
  - |
    bluegreen="true"
    ls -la
